# Generated by Django 5.1.7 on 2025-03-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_bannercards_bannercard_rename_cards_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercard',
            name='imageurl',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='imageurl',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
